#!/usr/bin/env bash
#
# Publish BiasharaMax into ~/public_html without a symlink or a document
# root change.
#
#   cd ~/biasharamax && bash deploy/publish-to-public-html.sh
#
# Run it again after every deploy — it re-copies the built assets, which
# change with every front-end build.
#
# ---------------------------------------------------------------------
# What this copies, and what it deliberately does not
#
# Only the contents of `backend/public/` go into the web root. The rest of
# the application — `.env`, `vendor/`, `app/`, `storage/` — stays in
# ~/biasharamax where the web server cannot serve it.
#
# That split is the entire security model of a Laravel app, not a
# preference. `.env` holds the database password, the mail password and
# APP_KEY. Copy the whole project into public_html and any of those is one
# URL away from anybody who guesses the filename — and they do guess; it is
# among the most scanned-for paths on the web. APP_KEY in particular signs
# every session cookie, so leaking it means anybody can forge a login.
#
# The only change needed to make this work is in index.php, which normally
# reaches one directory up for the autoloader. Here it reaches across to
# the real application directory instead.
# ---------------------------------------------------------------------

set -euo pipefail
trap 'echo; echo "FAILED at line $LINENO."; exit 1' ERR

cd "$(dirname "$0")/.."
ROOT="$(pwd)"
APP="$ROOT/backend"
WEB="${WEB_ROOT:-$HOME/public_html}"

echo "Publishing to $WEB"
echo "  application stays in $APP"
echo

if [ ! -d "$APP/public" ]; then
    echo "$APP/public does not exist. Is this the right directory?"
    exit 1
fi

if [ ! -f "$APP/vendor/autoload.php" ]; then
    echo "$APP/vendor is missing — run deploy/setup.sh first."
    exit 1
fi

# ---------------------------------------------------------------------
# Anything already there that is not ours gets moved aside, not deleted.
# This account has nine websites on it; deleting the web root outright is
# not a risk worth taking to save one command.
# ---------------------------------------------------------------------
if [ -f "$WEB/default.php" ]; then
    mkdir -p "$WEB/.replaced"
    mv "$WEB/default.php" "$WEB/.replaced/default.php"
    echo "  moved Hostinger's default.php to .replaced/"
fi

mkdir -p "$WEB"

echo "==> Copying public assets"
# The dot after public/ copies dotfiles too. Without it .htaccess is left
# behind, and Laravel's routing silently stops working — every URL except
# the homepage returns 404, which reads as a broken app rather than a
# missing file.
cp -R "$APP/public/." "$WEB/"

echo "==> Rewriting index.php for the split layout"
cat > "$WEB/index.php" <<PHP
<?php

use Illuminate\Foundation\Application;
use Illuminate\Http\Request;

define('LARAVEL_START', microtime(true));

/*
 * Generated by deploy/publish-to-public-html.sh — do not edit by hand.
 *
 * The application lives outside the web root, so the paths below are
 * absolute rather than the usual __DIR__.'/../'. Re-running the publish
 * script regenerates this file.
 */
\$app_base = '$APP';

if (file_exists(\$maintenance = \$app_base.'/storage/framework/maintenance.php')) {
    require \$maintenance;
}

require \$app_base.'/vendor/autoload.php';

/** @var Application \$app */
\$app = require_once \$app_base.'/bootstrap/app.php';

\$app->handleRequest(Request::capture());
PHP

echo "==> Re-pointing the storage link"
# `cp -R` copies public/storage as a symlink whose relative target no
# longer resolves from here. Uploaded images would 404 with nothing in the
# logs to explain it.
rm -rf "$WEB/storage"
ln -s "$APP/storage/app/public" "$WEB/storage"

echo
echo "==> Checking nothing private came along"
leaked=""
for f in .env .env.example composer.json artisan; do
    [ -e "$WEB/$f" ] && leaked="$leaked $f"
done

if [ -n "$leaked" ]; then
    echo "  STOP — these should not be in the web root:$leaked"
    echo "  Remove them before the site goes live."
    exit 1
fi
echo "    clean"

echo
echo "Published."
echo
echo "Check now:"
echo "  https://biasharamax.com/            → the BiasharaMax landing page"
echo "  https://biasharamax.com/.env        → must NOT return your config"
echo
echo "Re-run this script after every deploy, or the site will serve the"
echo "previous build's CSS and JavaScript."
